[package]
name = "voicevox-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5.0"
reqwest = "0.11.22"
tokio = {version = "1.34.0", features = ["macros", "rt-multi-thread", "signal"]}
